import { useCallback, useEffect, useState } from 'react'
import { Button, Dialog, DialogActions, DialogContent, DialogTitle, Grid, MenuItem, Paper, Snackbar, Stack, Tab, Table, TableBody, TableCell, TableHead, TableRow, Tabs, TextField, Typography } from '@mui/material'
import AddRoundedIcon from '@mui/icons-material/AddRounded'
import { useSearchParams } from 'react-router-dom'
import { api, type Category } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import { AdminUserCard, AccountStatus, CategorySlaCard, RoleLabel, duration, resolveAdminSection, roleLabel, workflowStatuses } from '../components/admin'
import { ResponsiveDataView } from '../components/resident'
import { ConfirmActionDialog, EmptyState, ErrorState, PageHeader, TableSkeleton } from '../components/ui'
import { formatDateTime } from '../components/formatting'

type AdminUser = { id: string; firstName: string; lastName: string; email: string; isActive: boolean; createdAtUtc: string; roles: string[] }
type PendingUserAction = { user: AdminUser; kind: 'role'; value: string } | { user: AdminUser; kind: 'active'; value: boolean }
const roles = ['Resident', 'CaseOfficer', 'TeamManager', 'SystemAdministrator']; const blankCategory = { name: '', description: '', firstResponseHours: 8, resolutionHours: 72 }

export function AdminPage() {
  const { user: current } = useAuth(); const [params, setParams] = useSearchParams(); const section = resolveAdminSection(params)
  const [users, setUsers] = useState<AdminUser[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false)
  const [categoryForm, setCategoryForm] = useState(blankCategory); const [editing, setEditing] = useState<Category | null>(null); const [categoryOpen, setCategoryOpen] = useState(false); const [pendingCategory, setPendingCategory] = useState<Category | null>(null)
  const [pending, setPending] = useState<PendingUserAction | null>(null); const [notice, setNotice] = useState(''); const [error, setError] = useState('')
  const load = useCallback(() => Promise.all([api<AdminUser[]>('/admin/users').then(setUsers), api<Category[]>('/admin/categories').then(setCategories)]).then(() => setLoading(false)).catch(reason => { setLoading(false); setError(reason instanceof Error ? reason.message : 'Unable to load administration data') }), [])
  useEffect(() => { void load() }, [load])
  const changeSection = (value: string) => { const next = new URLSearchParams(params); next.set('section', value); setParams(next) }
  const openCategory = (category?: Category) => { setEditing(category ?? null); setCategoryForm(category ? { name: category.name, description: category.description, firstResponseHours: category.firstResponseHours, resolutionHours: category.resolutionHours } : blankCategory); setCategoryOpen(true) }
  const saveCategory = async () => { if (busy) return; setBusy(true); setError(''); try { await api(editing ? `/admin/categories/${editing.id}` : '/admin/categories', { method: editing ? 'PUT' : 'POST', body: JSON.stringify(categoryForm) }); setCategoryOpen(false); setNotice(editing ? 'Category updated.' : 'Category created.'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save category') } finally { setBusy(false) } }
  const toggleCategory = async () => { if (!pendingCategory || busy) return; setBusy(true); try { await api(`/admin/categories/${pendingCategory.id}/active`, { method: 'PUT', body: JSON.stringify({ isActive: !pendingCategory.isActive }) }); setNotice(pendingCategory.isActive ? 'Category disabled.' : 'Category enabled.'); setPendingCategory(null); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update category') } finally { setBusy(false) } }
  const confirmUserAction = async () => { if (!pending || busy) return; setBusy(true); try { if (pending.kind === 'role') await api(`/admin/users/${pending.user.id}/role`, { method: 'PUT', body: JSON.stringify({ role: pending.value }) }); else await api(`/admin/users/${pending.user.id}/active`, { method: 'PUT', body: JSON.stringify({ isActive: pending.value }) }); setNotice('User access updated.'); setPending(null); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update user'); setPending(null) } finally { setBusy(false) } }
  const userActions = (user: AdminUser) => { const self = user.id === current?.id; return <><TextField select size="small" label="Change role" disabled={self || busy} value={user.roles[0] ?? 'Resident'} onChange={event => setPending({ user, kind: 'role', value: event.target.value })}>{roles.map(role => <MenuItem value={role} key={role}>{roleLabel(role)}</MenuItem>)}</TextField><Button disabled={self || busy} color={user.isActive ? 'warning' : 'success'} onClick={() => setPending({ user, kind: 'active', value: !user.isActive })}>{user.isActive ? 'Disable account' : 'Enable account'}</Button></> }
  return <Stack spacing={4}><PageHeader title="System administration" description="Manage user access and service categories, or review the case workflow reference." actions={section === 'categories' && <Button startIcon={<AddRoundedIcon />} variant="contained" onClick={() => openCategory()}>New category</Button>} />
    <Tabs value={section} onChange={(_, value) => changeSection(value)} variant="scrollable" scrollButtons="auto" aria-label="Administration sections"><Tab value="users" label="Users" /><Tab value="categories" label="Categories & SLA" /><Tab value="workflow" label="Workflow statuses" /></Tabs>
    {error && <ErrorState title="Administration action failed" message={error} retry={() => void load()} />}{loading && <Paper><TableSkeleton rows={5} columns={4} /></Paper>}
    {!loading && section === 'users' && <Stack spacing={3}><Typography variant="h5">Users ({users.length})</Typography><Typography color="text.secondary">Current access and actions are shown separately. Your own administrator access is protected.</Typography><ResponsiveDataView desktop={<Paper sx={{ overflowX: 'auto' }}><Table><TableHead><TableRow><TableCell>Name</TableCell><TableCell>Email</TableCell><TableCell>Role</TableCell><TableCell>Status</TableCell><TableCell>Created</TableCell><TableCell>Actions</TableCell></TableRow></TableHead><TableBody>{users.map(user => { const self = user.id === current?.id; return <TableRow key={user.id}><TableCell>{user.firstName} {user.lastName}{self ? ' (You)' : ''}</TableCell><TableCell sx={{ overflowWrap: 'anywhere' }}>{user.email}</TableCell><TableCell><RoleLabel role={user.roles[0] ?? 'Resident'} /></TableCell><TableCell><AccountStatus active={user.isActive} /></TableCell><TableCell>{formatDateTime(user.createdAtUtc)}</TableCell><TableCell><Stack direction="row">{userActions(user)}</Stack></TableCell></TableRow> })}</TableBody></Table></Paper>} mobile={<Stack spacing={3}>{users.map(user => <AdminUserCard key={user.id} user={user} self={user.id === current?.id} actions={userActions(user)} />)}</Stack>} /></Stack>}
    {!loading && section === 'categories' && <Stack spacing={3}><Typography variant="h5">Categories & SLA ({categories.length})</Typography><Typography color="text.secondary">Targets apply to new cases. Disabling a category does not change historical cases.</Typography><ResponsiveDataView desktop={<Paper sx={{ overflowX: 'auto' }}><Table><TableHead><TableRow><TableCell>Category</TableCell><TableCell>Status</TableCell><TableCell>First response</TableCell><TableCell>Resolution</TableCell><TableCell>Actions</TableCell></TableRow></TableHead><TableBody>{categories.map(category => <TableRow key={category.id}><TableCell><strong>{category.name}</strong><Typography color="text.secondary">{category.description}</Typography></TableCell><TableCell><AccountStatus active={category.isActive} /></TableCell><TableCell>{duration(category.firstResponseHours)}</TableCell><TableCell>{duration(category.resolutionHours)}</TableCell><TableCell><Button onClick={() => openCategory(category)}>Edit</Button><Button color={category.isActive ? 'warning' : 'success'} onClick={() => setPendingCategory(category)}>{category.isActive ? 'Disable category' : 'Enable category'}</Button></TableCell></TableRow>)}</TableBody></Table></Paper>} mobile={<Stack spacing={3}>{categories.map(category => <CategorySlaCard key={category.id} category={category} actions={<><Button onClick={() => openCategory(category)}>Edit</Button><Button color={category.isActive ? 'warning' : 'success'} onClick={() => setPendingCategory(category)}>{category.isActive ? 'Disable' : 'Enable'}</Button></>} />)}</Stack>} /></Stack>}
    {!loading && section === 'workflow' && <Stack spacing={3}><Typography variant="h5">Workflow statuses ({workflowStatuses.length})</Typography><Typography color="text.secondary">Statuses are controlled by the case workflow. They cannot be added, edited or deleted here.</Typography><Grid container spacing={3}>{workflowStatuses.map(status => <Grid size={{ xs: 12, md: 6 }} key={status.name}><Paper sx={{ p: 4, height: '100%' }}><Typography variant="h6">{status.name}</Typography><Typography color="text.secondary">{status.description}</Typography></Paper></Grid>)}</Grid></Stack>}
    {!loading && section !== 'workflow' && ((section === 'users' && !users.length) || (section === 'categories' && !categories.length)) && <EmptyState title="No records available" />}
    <Dialog open={categoryOpen} onClose={() => !busy && setCategoryOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{editing ? 'Edit service category' : 'New service category'}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label="Name" required value={categoryForm.name} onChange={event => setCategoryForm({ ...categoryForm, name: event.target.value })} /><TextField label="Description" multiline minRows={3} required value={categoryForm.description} onChange={event => setCategoryForm({ ...categoryForm, description: event.target.value })} /><Grid container spacing={2}><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth label="First response hours" type="number" slotProps={{ htmlInput: { min: 1 } }} value={categoryForm.firstResponseHours} onChange={event => setCategoryForm({ ...categoryForm, firstResponseHours: Number(event.target.value) })} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth label="Resolution hours" type="number" slotProps={{ htmlInput: { min: 1 } }} value={categoryForm.resolutionHours} onChange={event => setCategoryForm({ ...categoryForm, resolutionHours: Number(event.target.value) })} /></Grid></Grid></Stack></DialogContent><DialogActions><Button disabled={busy} onClick={() => setCategoryOpen(false)}>Cancel</Button><Button variant="contained" disabled={busy || categoryForm.firstResponseHours < 1 || categoryForm.resolutionHours < 1} onClick={saveCategory}>{busy ? 'Saving…' : 'Save category'}</Button></DialogActions></Dialog>
    <ConfirmActionDialog open={Boolean(pending)} title="Confirm user access change" description={pending?.kind === 'role' ? `Change ${pending.user.email} from ${roleLabel(pending.user.roles[0] ?? 'Resident')} to ${roleLabel(pending.value)}?` : `${pending?.value ? 'Enable' : 'Disable'} ${pending?.user.email}?`} confirmLabel="Confirm change" busy={busy} onCancel={() => setPending(null)} onConfirm={confirmUserAction} />
    <ConfirmActionDialog open={Boolean(pendingCategory)} title={`${pendingCategory?.isActive ? 'Disable' : 'Enable'} category?`} description={pendingCategory?.isActive ? 'Residents will no longer be able to select this category for new requests. Existing cases are unchanged.' : 'Residents will be able to select this category for new requests.'} confirmLabel={pendingCategory?.isActive ? 'Disable category' : 'Enable category'} busy={busy} onCancel={() => setPendingCategory(null)} onConfirm={toggleCategory} />
    <Snackbar open={Boolean(notice)} autoHideDuration={3500} onClose={() => setNotice('')} message={notice} />
  </Stack>
}
