import { useEffect, useState } from 'react'
import { Alert, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Grid, MenuItem, Paper, Snackbar, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material'
import AddRoundedIcon from '@mui/icons-material/AddRounded'
import { api, type Category } from '../api/client'
import { useAuth } from '../auth/AuthContext'

type AdminUser = { id: string; firstName: string; lastName: string; email: string; isActive: boolean; createdAtUtc: string; roles: string[] }
type PendingUserAction = { user: AdminUser; kind: 'role'; value: string } | { user: AdminUser; kind: 'active'; value: boolean }
const roles = ['Resident', 'CaseOfficer', 'TeamManager', 'SystemAdministrator']
const blankCategory = { name: '', description: '', firstResponseHours: 8, resolutionHours: 72 }

export function AdminPage() {
  const { user: current } = useAuth(); const [users, setUsers] = useState<AdminUser[]>([]); const [categories, setCategories] = useState<Category[]>([])
  const [categoryForm, setCategoryForm] = useState(blankCategory); const [editing, setEditing] = useState<Category | null>(null); const [categoryOpen, setCategoryOpen] = useState(false)
  const [pending, setPending] = useState<PendingUserAction | null>(null); const [notice, setNotice] = useState(''); const [error, setError] = useState('')
  const load = () => Promise.all([api<AdminUser[]>('/admin/users').then(setUsers), api<Category[]>('/admin/categories').then(setCategories)])
  useEffect(() => { void load().catch(e => setError(e instanceof Error ? e.message : 'Unable to load administration data')) }, [])
  const openCategory = (category?: Category) => { setEditing(category ?? null); setCategoryForm(category ? { name: category.name, description: category.description, firstResponseHours: category.firstResponseHours, resolutionHours: category.resolutionHours } : blankCategory); setCategoryOpen(true) }
  const saveCategory = async () => { setError(''); try { await api(editing ? `/admin/categories/${editing.id}` : '/admin/categories', { method: editing ? 'PUT' : 'POST', body: JSON.stringify(categoryForm) }); setCategoryOpen(false); setNotice(editing ? 'Category updated.' : 'Category created.'); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save category') } }
  const toggleCategory = async (category: Category) => { try { await api(`/admin/categories/${category.id}/active`, { method: 'PUT', body: JSON.stringify({ isActive: !category.isActive }) }); setNotice(category.isActive ? 'Category disabled.' : 'Category enabled.'); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update category') } }
  const confirmUserAction = async () => { if (!pending) return; try { if (pending.kind === 'role') await api(`/admin/users/${pending.user.id}/role`, { method: 'PUT', body: JSON.stringify({ role: pending.value }) }); else await api(`/admin/users/${pending.user.id}/active`, { method: 'PUT', body: JSON.stringify({ isActive: pending.value }) }); setNotice('User access updated.'); setPending(null); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update user'); setPending(null) } }
  return <Stack spacing={4}><Stack direction={{ xs: 'column', sm: 'row' }} sx={{ justifyContent: 'space-between', gap: 2 }}><div><Typography variant="h3">System administration</Typography><Typography color="text.secondary">Manage service categories, SLA defaults and user access.</Typography></div><Button startIcon={<AddRoundedIcon />} variant="contained" onClick={() => openCategory()}>New category</Button></Stack>{error && <Alert severity="error" onClose={() => setError('')}>{error}</Alert>}
    <Paper sx={{ overflowX: 'auto' }}><Stack sx={{ p: 3 }}><Typography variant="h5" sx={{ fontWeight: 800 }}>Service categories</Typography><Typography color="text.secondary">Categories referenced by cases remain available for history and can only be disabled.</Typography></Stack><Table><TableHead><TableRow><TableCell>Name</TableCell><TableCell>Description</TableCell><TableCell>First response SLA</TableCell><TableCell>Resolution SLA</TableCell><TableCell>Status</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{categories.map(category => <TableRow key={category.id}><TableCell><strong>{category.name}</strong></TableCell><TableCell>{category.description}</TableCell><TableCell>{category.firstResponseHours}h</TableCell><TableCell>{category.resolutionHours}h</TableCell><TableCell><Chip size="small" color={category.isActive ? 'success' : 'default'} label={category.isActive ? 'Active' : 'Disabled'} /></TableCell><TableCell align="right"><Button onClick={() => openCategory(category)}>Edit</Button><Button color={category.isActive ? 'warning' : 'success'} onClick={() => toggleCategory(category)}>{category.isActive ? 'Disable' : 'Enable'}</Button></TableCell></TableRow>)}</TableBody></Table></Paper>
    <Paper sx={{ overflowX: 'auto' }}><Stack sx={{ p: 3 }}><Typography variant="h5" sx={{ fontWeight: 800 }}>User access</Typography><Typography color="text.secondary">Role and account changes require confirmation. Your own administrator access is protected.</Typography></Stack><Table><TableHead><TableRow><TableCell>User</TableCell><TableCell>Role</TableCell><TableCell>Status</TableCell><TableCell>Created</TableCell></TableRow></TableHead><TableBody>{users.map(user => { const self = user.id === current?.id; return <TableRow key={user.id}><TableCell>{user.firstName} {user.lastName}{self && <Chip label="You" size="small" sx={{ ml: 1 }} />}<Typography variant="caption" color="text.secondary" sx={{ display: 'block' }}>{user.email}</Typography></TableCell><TableCell><TextField select size="small" disabled={self} value={user.roles[0] ?? 'Resident'} onChange={e => setPending({ user, kind: 'role', value: e.target.value })}>{roles.map(role => <MenuItem value={role} key={role}>{role}</MenuItem>)}</TextField></TableCell><TableCell><Button disabled={self} color={user.isActive ? 'success' : 'error'} onClick={() => setPending({ user, kind: 'active', value: !user.isActive })}>{user.isActive ? 'Active' : 'Disabled'}</Button></TableCell><TableCell>{new Date(user.createdAtUtc).toLocaleDateString()}</TableCell></TableRow> })}</TableBody></Table></Paper>
    <Dialog open={categoryOpen} onClose={() => setCategoryOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{editing ? 'Edit service category' : 'New service category'}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label="Name" required value={categoryForm.name} onChange={e => setCategoryForm({ ...categoryForm, name: e.target.value })} /><TextField label="Description" multiline minRows={3} required value={categoryForm.description} onChange={e => setCategoryForm({ ...categoryForm, description: e.target.value })} /><Grid container spacing={2}><Grid size={6}><TextField fullWidth label="First response hours" type="number" value={categoryForm.firstResponseHours} onChange={e => setCategoryForm({ ...categoryForm, firstResponseHours: Number(e.target.value) })} /></Grid><Grid size={6}><TextField fullWidth label="Resolution hours" type="number" value={categoryForm.resolutionHours} onChange={e => setCategoryForm({ ...categoryForm, resolutionHours: Number(e.target.value) })} /></Grid></Grid></Stack></DialogContent><DialogActions><Button onClick={() => setCategoryOpen(false)}>Cancel</Button><Button variant="contained" onClick={saveCategory}>Save category</Button></DialogActions></Dialog>
    <Dialog open={Boolean(pending)} onClose={() => setPending(null)}><DialogTitle>Confirm user access change</DialogTitle><DialogContent><Typography>{pending?.kind === 'role' ? `Change ${pending.user.email} role to ${pending.value}?` : `${pending?.value ? 'Enable' : 'Disable'} ${pending?.user.email}?`}</Typography></DialogContent><DialogActions><Button onClick={() => setPending(null)}>Cancel</Button><Button color="warning" variant="contained" onClick={confirmUserAction}>Confirm change</Button></DialogActions></Dialog>
    <Snackbar open={Boolean(notice)} autoHideDuration={3500} onClose={() => setNotice('')} message={notice} />
  </Stack>
}
