import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Button, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TablePagination, TableRow, TextField, Typography } from '@mui/material'
import { Link, useSearchParams } from 'react-router-dom'
import { api, type PagedResponse } from '../api/client'
import { AuditEventCard, auditAction, hasAuditFilters, updateAdminQuery } from '../components/admin'
import { ActiveFilterSummary, ResponsiveDataView } from '../components/resident'
import { EmptyState, ErrorState, PageHeader, TableSkeleton } from '../components/ui'
import { formatDateTime } from '../components/formatting'
import { useDebouncedValue } from '../hooks/useDebouncedValue'

type AdminUser = { id: string; firstName: string; lastName: string; email: string }
type AuditRow = { id: string; action: string; message: string; createdAtUtc: string; serviceRequestId: string; actorId: string; userName?: string; userEmail?: string; referenceNumber?: string }

export function AuditLogPage() {
  const [params, setParams] = useSearchParams(); const debouncedAction = useDebouncedValue(params.get('action') ?? ''); const debouncedCase = useDebouncedValue(params.get('case') ?? ''); const immediateQuery = useMemo(() => { const value = new URLSearchParams(params); value.delete('action'); value.delete('case'); return value.toString() }, [params]); const requestSequence = useRef(0); const [data, setData] = useState<PagedResponse<AuditRow> | null>(null); const [users, setUsers] = useState<AdminUser[]>([]); const [error, setError] = useState('')
  useEffect(() => { void api<AdminUser[]>('/admin/audit-users').then(setUsers).catch(reason => setError(reason instanceof Error ? reason.message : 'Unable to load actors')) }, [])
  const load = useCallback(() => { const query = new URLSearchParams(immediateQuery); if (debouncedAction) query.set('action', debouncedAction); if (debouncedCase) query.set('case', debouncedCase); const sequence = ++requestSequence.current; return api<PagedResponse<AuditRow>>(`/admin/audit-logs${query.size ? `?${query}` : ''}`).then(result => { if (sequence === requestSequence.current) { setData(result); setError('') } }).catch(reason => { if (sequence === requestSequence.current) setError(reason instanceof Error ? reason.message : 'Unable to load audit log') }) }, [immediateQuery, debouncedAction, debouncedCase])
  useEffect(() => { void load() }, [load]); const update = (key: string, value: string) => setParams(updateAdminQuery(params, key, value)); const clear = () => setParams(new URLSearchParams())
  const page = Number(params.get('page') ?? '1'); const pageSize = Number(params.get('pageSize') ?? '25'); const filtersActive = hasAuditFilters(params)
  return <Stack spacing={3}><PageHeader title="Audit log" description={`Read-only system-level history for authorised managers and administrators.${data ? ` ${data.totalCount} result${data.totalCount === 1 ? '' : 's'}.` : ''}`} />
    <Paper sx={{ p: 3 }}><Stack direction={{ xs: 'column', md: 'row' }} spacing={2} useFlexGap sx={{ flexWrap: 'wrap' }}><TextField select size="small" label="Actor" value={params.get('userId') ?? ''} onChange={event => update('userId', event.target.value)} sx={{ minWidth: 220 }}><MenuItem value="">All actors</MenuItem>{users.map(user => <MenuItem key={user.id} value={user.id}>{user.firstName} {user.lastName}</MenuItem>)}</TextField><TextField size="small" label="Action or type" value={params.get('action') ?? ''} onChange={event => update('action', event.target.value)} /><TextField size="small" label="Case reference or title" value={params.get('case') ?? ''} onChange={event => update('case', event.target.value)} /><TextField size="small" type="date" label="Date from" value={params.get('from')?.slice(0, 10) ?? ''} onChange={event => update('from', event.target.value)} slotProps={{ inputLabel: { shrink: true } }} /><TextField size="small" type="date" label="Date to" value={params.get('to')?.slice(0, 10) ?? ''} onChange={event => update('to', event.target.value)} slotProps={{ inputLabel: { shrink: true } }} />{filtersActive && <Button onClick={clear}>Clear filters</Button>}</Stack></Paper>
    {filtersActive && <ActiveFilterSummary search={params.get('case') ?? params.get('action') ?? undefined} status={params.get('userId') ? 'Actor selected' : undefined} onClear={clear} />}
    {error && <ErrorState title="Unable to load audit log" message={error} retry={() => { setError(''); void load() }} />}{!data && !error && <Paper><TableSkeleton columns={5} /></Paper>}
    {data && <ResponsiveDataView desktop={<Paper sx={{ overflowX: 'auto' }}><Table><TableHead><TableRow><TableCell>Time</TableCell><TableCell>Action</TableCell><TableCell>Actor</TableCell><TableCell>Case</TableCell><TableCell>Summary</TableCell></TableRow></TableHead><TableBody>{data.items.map(row => <TableRow key={row.id}><TableCell sx={{ whiteSpace: 'nowrap' }}>{formatDateTime(row.createdAtUtc)}</TableCell><TableCell>{auditAction(row.action)}</TableCell><TableCell sx={{ minWidth: 220, maxWidth: 280 }}><Typography>{row.userName ?? 'System'}</Typography>{row.userEmail && <Typography variant="caption" title={row.userEmail} noWrap sx={{ display: 'block', maxWidth: 260 }} color="text.secondary">{row.userEmail}</Typography>}</TableCell><TableCell sx={{ minWidth: 170 }}>{row.referenceNumber ? <Button component={Link} to={`/cases/${row.serviceRequestId}`} sx={{ whiteSpace: 'nowrap' }}>{row.referenceNumber}</Button> : '—'}</TableCell><TableCell sx={{ minWidth: 260, overflowWrap: 'anywhere' }}>{row.message}</TableCell></TableRow>)}{!data.items.length && <TableRow><TableCell colSpan={5}><EmptyState title="No audit events" description="No audit events match the current filters." /></TableCell></TableRow>}</TableBody></Table></Paper>} mobile={<Stack spacing={3}>{data.items.map(row => <AuditEventCard key={row.id} row={row} />)}{!data.items.length && <Paper><EmptyState title="No audit events" description="No audit events match the current filters." /></Paper>}</Stack>} />}
    {data && <Paper><TablePagination component="div" count={data.totalCount} page={Math.max(0, page - 1)} rowsPerPage={pageSize} rowsPerPageOptions={[25, 50, 100]} onPageChange={(_, next) => update('page', String(next + 1))} onRowsPerPageChange={event => update('pageSize', event.target.value)} /></Paper>}
  </Stack>
}
