import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react'
import { Alert, Box, Button, Divider, Grid, MenuItem, Paper, Snackbar, Stack, TextField, Typography } from '@mui/material'
import { Link, useParams } from 'react-router-dom'
import { api, type Activity, type CaseDetail, type Officer } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import { CaseAttachments } from '../components/CaseAttachments'
import { ConfirmActionDialog, ErrorState, PageHeader, PageLoading, PriorityChip, SectionCard, SlaStatus, StatusChip } from '../components/ui'
import { CharacterCounter, InlineNotice, TimelineItem } from '../components/resident'
import { formatDateTime } from '../components/formatting'

const CaseMap = lazy(() => import('../components/CaseMap').then(module => ({ default: module.CaseMap })))

const priorities = ['Low', 'Medium', 'High', 'Critical']

export function CaseDetailPage() {
  const { id } = useParams(); const { user } = useAuth(); const resident = user?.roles.includes('Resident'); const isOfficer = user?.roles.includes('CaseOfficer')
  const canManage = user?.roles.some(x => x === 'TeamManager' || x === 'SystemAdministrator') ?? false
  const [detail, setDetail] = useState<CaseDetail | null>(null); const [message, setMessage] = useState(''); const [internal, setInternal] = useState(false)
  const [priority, setPriority] = useState('Medium'); const [firstDue, setFirstDue] = useState(''); const [resolutionDue, setResolutionDue] = useState('')
  const [officers, setOfficers] = useState<Officer[]>([]); const [officerId, setOfficerId] = useState(''); const [resolutionSummary, setResolutionSummary] = useState('')
  const lock = useRef(false); const messageKey = useRef(crypto.randomUUID()); const [reopenReason, setReopenReason] = useState(''); const [confirmReopen, setConfirmReopen] = useState(false)
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false)
  const load = useCallback(() => api<CaseDetail>(`/cases/${id}`).then(data => { setDetail(data); setPriority(data.case.priority); setFirstDue(toLocal(data.case.firstResponseDueAtUtc)); setResolutionDue(toLocal(data.case.resolutionDueAtUtc)); setOfficerId(data.case.assignedOfficerId ?? '') }).catch(e => setError(e instanceof Error ? e.message : 'Unable to load request')), [id])
  useEffect(() => { void load() }, [load])
  useEffect(() => { if (canManage) void api<Officer[]>('/officers').then(setOfficers) }, [canManage])

  const run = async (success: string, action: () => Promise<unknown>) => { if (lock.current) return; lock.current = true; setBusy(true); setError(''); try { await action(); await load(); setNotice(success); return true } catch (e) { setError(e instanceof Error ? e.message : 'Operation failed'); return false } finally { lock.current = false; setBusy(false) } }
  const comment = () => run('Message sent.', async () => { if (!message.trim()) throw new Error('Enter a message.'); await api(`/cases/${id}/comments`, { method: 'POST', headers: { 'Idempotency-Key': messageKey.current }, body: JSON.stringify({ message, internal }) }); setMessage(''); messageKey.current = crypto.randomUUID() })
  const saveTriage = () => run('Priority and SLA updated.', () => api(`/cases/${id}/triage`, { method: 'POST', body: JSON.stringify({ priority, firstResponseDueAtUtc: firstDue ? new Date(firstDue).toISOString() : null, resolutionDueAtUtc: resolutionDue ? new Date(resolutionDue).toISOString() : null }) }))
  const assign = () => run(detail?.case.assignedOfficerId ? 'Case reassigned.' : 'Case assigned.', async () => { if (!officerId) throw new Error('Select an officer.'); await api(`/cases/${id}/assign`, { method: 'POST', body: JSON.stringify({ officerId }) }) })
  const status = (next: string, note = '') => run(next === 'Resolved' ? 'Case resolved.' : 'Case status updated.', () => api(`/cases/${id}/status`, { method: 'POST', body: JSON.stringify({ status: next, note }) }))

  if (!detail && error) return <ErrorState title="Unable to load request" message={error} retry={() => void load()} />; if (!detail) return <PageLoading label="Loading request" />
  const item = detail.case; const assignedToMe = item.assignedOfficerId === user?.id
  if (resident) {
    const progress = detail.activities.filter(activity => activity.section === 'progress')
    const conversation = detail.activities.filter(activity => activity.section === 'conversation')
    const resolution = progress.find(activity => activity.type === 'Resolved')
    return <Stack spacing={5}><Button component={Link} to="/requests" sx={{ alignSelf: 'flex-start' }}>← Back to my requests</Button><PageHeader eyebrow={item.referenceNumber} title={item.title} description={residentProgress(item.status)} /><Stack direction="row" spacing={2} useFlexGap sx={{ flexWrap: 'wrap', mt: -3 }}><StatusChip status={item.status} /><SlaStatus state={item.slaState} label={item.slaState === 'Complete' ? 'Service target complete' : item.slaState === 'Overdue' ? 'Service target overdue' : item.slaState === 'AtRisk' ? 'Service target due soon' : 'Service target on track'} /></Stack>
      {error && <ErrorState title="Request action failed" message={error} />}{notice && <InlineNotice severity="success">{notice}</InlineNotice>}
      <SectionCard title="Request summary"><Grid container spacing={4}><Grid size={{ xs: 12, sm: 6 }}><Typography variant="overline" color="text.secondary">Category</Typography><Typography sx={{ fontWeight: 800, overflowWrap: 'anywhere' }}>{detail.category.name}</Typography></Grid><Grid size={{ xs: 12, sm: 6 }}><Typography variant="overline" color="text.secondary">Submitted</Typography><Typography sx={{ fontWeight: 800 }}>{formatDateTime(item.submittedAtUtc)}</Typography></Grid><Grid size={12}><Typography variant="overline" color="text.secondary">Current progress</Typography><Typography sx={{ fontWeight: 800 }}>{residentProgress(item.status)}</Typography></Grid></Grid></SectionCard>
      <SectionCard title="Request information"><Typography sx={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{item.description}</Typography><Typography color="text.secondary" sx={{ mt: 4, overflowWrap: 'anywhere' }}><strong>Address:</strong> {item.address}</Typography></SectionCard>
      <SectionCard title="Request progress" description="Key updates about your request appear here.">{progress.length ? progress.map(activity => <TimelineItem key={activity.id} title={activity.label} message={activity.message} meta={`${formatDateTime(activity.createdAtUtc)}${activity.actorName ? ` · ${activity.actorName}` : ''}`} />) : <Typography color="text.secondary">No progress milestones yet.</Typography>}</SectionCard>
      <SectionCard title="Conversation" description="Public messages between you and the service team."><Stack spacing={5}>{conversation.length ? conversation.map(activity => <TimelineItem key={activity.id} title={activity.label} message={activity.message} meta={`${formatDateTime(activity.createdAtUtc)}${activity.actorName ? ` · ${activity.actorName}` : ''}`} />) : <Typography color="text.secondary">No messages yet.</Typography>}<Divider /><TextField fullWidth multiline rows={3} value={message} onChange={event => { setMessage(event.target.value); messageKey.current = crypto.randomUUID() }} label="Reply to the service team" helperText="Your reply will be visible to authorised service staff." /><Button variant="contained" disabled={busy || !message.trim()} onClick={comment} sx={{ alignSelf: { sm: 'flex-start' } }}>{busy ? 'Sending reply…' : 'Send reply'}</Button></Stack></SectionCard>
      <CaseAttachments caseId={item.id} status={item.status} resident canEdit />
      <SectionCard title="Location" description="This map shows the location pin supplied with your request. The written address remains available if the map is unavailable."><Typography sx={{ fontWeight: 800, overflowWrap: 'anywhere' }}>{item.address}</Typography><Suspense fallback={<PageLoading label="Loading map" />}><CaseMap latitude={item.latitude} longitude={item.longitude} /></Suspense></SectionCard>
      {resolution && <SectionCard title="Resolution summary"><InlineNotice severity="success" title="Service work completed">{resolution.message}</InlineNotice></SectionCard>}
      {item.status === 'Resolved' && <SectionCard title="Need more help?" description="If the issue is not resolved, you can reopen the request. The original history and service target remain attached."><Button variant="contained" color="warning" disabled={busy} onClick={() => setConfirmReopen(true)}>{busy ? 'Working…' : 'Reopen request'}</Button></SectionCard>}
      {item.status === 'Closed' && <InlineNotice>This request is closed. Its public history and files remain available for your records.</InlineNotice>}
      {item.status === 'Rejected' && <InlineNotice severity="warning">This request is not proceeding. Review the public reason in Request progress.</InlineNotice>}
      <ConfirmActionDialog open={confirmReopen} title="Reopen this request?" description="The original service target and history will be retained. Tell the service team why further work is needed." confirmLabel="Confirm reopen" busy={busy} confirmDisabled={reopenReason.trim().length < 10 || reopenReason.trim().length > 1800} onCancel={() => setConfirmReopen(false)} onConfirm={() => { void status('Reopened', reopenReason).then(ok => { if (ok) setConfirmReopen(false) }) }}><TextField autoFocus fullWidth multiline rows={4} label="Reason" value={reopenReason} onChange={event => setReopenReason(event.target.value)} slotProps={{ htmlInput: { maxLength: 1800, 'aria-describedby': 'reopen-reason-count' } }} helperText={<Stack component="span" direction="row" sx={{ justifyContent: 'space-between', gap: 2 }}><span>Enter 10–1800 characters.</span><CharacterCounter id="reopen-reason-count" current={reopenReason.length} max={1800} /></Stack>} /></ConfirmActionDialog>
      <Snackbar open={Boolean(notice)} autoHideDuration={3500} onClose={() => setNotice('')} message={notice} />
    </Stack>
  }
  return <Stack spacing={3}><PageHeader eyebrow={item.referenceNumber} title={item.title} actions={<Stack direction="row" spacing={1} useFlexGap sx={{ flexWrap: 'wrap' }}><StatusChip status={item.status} /><PriorityChip priority={item.priority} variant="outlined" /><SlaStatus state={item.slaState} label={item.slaState === 'Complete' ? 'Overall SLA · Complete' : `Overall SLA · ${format(item.slaState)} · ${item.nextSlaTarget ?? 'Target'} ${slaRemaining(item.nextSlaDueAtUtc)}`} /></Stack>} />
    {error && <Alert severity="error" onClose={() => setError('')}>{error}</Alert>}
    <Grid container spacing={3}><Grid size={{ xs: 12, md: 8 }}><Stack spacing={3}><SectionCard title="Request details"><Typography sx={{ whiteSpace: 'pre-wrap' }}>{item.description}</Typography><Typography color="text.secondary" sx={{ mt: 2 }}><strong>Location:</strong> {item.address}</Typography><Typography color="text.secondary"><strong>Category:</strong> {detail.category.name}</Typography><Typography color="text.secondary"><strong>Assigned officer:</strong> {item.assignedOfficerName ?? 'Unassigned'}</Typography><Suspense fallback={<PageLoading label="Loading map" />}><CaseMap latitude={item.latitude} longitude={item.longitude} /></Suspense></SectionCard>
      <CaseAttachments caseId={item.id} status={item.status} resident={Boolean(resident)} canEdit={Boolean(resident || canManage || (isOfficer && assignedToMe))} />
      {resident && <Feed title="Request progress" items={detail.activities.filter(a => a.section === 'progress')} />}
      <Feed title="Conversation" items={detail.activities.filter(a => a.section === 'conversation')} />
      {!resident && <><Feed title="Internal notes" items={detail.activities.filter(a => a.section === 'internal')} /><Feed title="Case activity" items={detail.activities.filter(a => a.section === 'progress')} /></>}
      {canManage && <Button component={Link} to={`/admin/audit-log?case=${encodeURIComponent(item.referenceNumber)}`}>View full audit log</Button>}
      <Paper sx={{ p: 3 }}><Typography variant="h6" sx={{ fontWeight: 800 }}>{resident ? 'Reply to the service team' : 'Send a message or internal note'}</Typography><TextField fullWidth multiline minRows={3} value={message} onChange={e => { setMessage(e.target.value); messageKey.current = crypto.randomUUID() }} sx={{ my: 2 }} label="Message" />{!resident && <Button variant={internal ? 'contained' : 'outlined'} color="warning" disabled={busy} onClick={() => { setInternal(!internal); messageKey.current = crypto.randomUUID() }} sx={{ mr: 2 }}>{internal ? 'Internal note selected' : 'Make internal'}</Button>}<Button variant="contained" disabled={busy || !message.trim() || (isOfficer && !assignedToMe)} onClick={comment}>{resident ? 'Send reply' : internal ? 'Save internal note' : 'Send message'}</Button></Paper></Stack></Grid>
      <Grid size={{ xs: 12, md: 4 }}><Stack spacing={3}><Paper sx={{ p: 3 }}><Typography variant="h6" sx={{ fontWeight: 800 }}>Service targets</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>Category defaults: first response {detail.category.firstResponseHours}h · resolution {detail.category.resolutionHours}h</Typography><Divider sx={{ my: 2 }} /><SlaTarget label="First response" due={item.firstResponseDueAtUtc} completed={item.firstResponseCompletedAtUtc} state={item.firstResponseSlaState} /><Divider sx={{ my: 2 }} /><SlaTarget label="Resolution" due={item.resolutionDueAtUtc} state={item.resolutionSlaState} /></Paper>
      {canManage && <Paper sx={{ p: 3 }}><Typography variant="h6" sx={{ fontWeight: 800 }}>Triage & SLA</Typography><TextField select fullWidth label="Priority" value={priority} onChange={e => setPriority(e.target.value)} sx={{ mt: 2 }}>{priorities.map(x => <MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField fullWidth type="datetime-local" label="First response due" value={firstDue} onChange={e => setFirstDue(e.target.value)} slotProps={{ inputLabel: { shrink: true } }} sx={{ mt: 2 }} /><TextField fullWidth type="datetime-local" label="Resolution due" value={resolutionDue} onChange={e => setResolutionDue(e.target.value)} slotProps={{ inputLabel: { shrink: true } }} sx={{ mt: 2 }} /><Button fullWidth variant="contained" disabled={busy} onClick={saveTriage} sx={{ mt: 2 }}>Save priority & SLA</Button><Button fullWidth disabled={busy || ['Resolved', 'Closed', 'Rejected'].includes(item.status)} onClick={() => void run('SLA recalculated from submission.', () => api(`/cases/${id}/triage`, { method: 'POST', body: JSON.stringify({ priority }) }))}>Recalculate from submission</Button><Divider sx={{ my: 3 }} /><TextField select fullWidth label={item.assignedOfficerId ? 'Reassign officer' : 'Assign officer'} value={officerId} onChange={e => setOfficerId(e.target.value)}>{officers.map(x => <MenuItem key={x.id} value={x.id}>{x.firstName} {x.lastName}</MenuItem>)}</TextField><Button fullWidth variant="outlined" disabled={busy || !officerId} onClick={assign} sx={{ mt: 1 }}>{item.assignedOfficerId ? 'Reassign case' : 'Assign case'}</Button></Paper>}
      {isOfficer && <Paper sx={{ p: 3 }}><Typography variant="h6" sx={{ fontWeight: 800 }}>Next action</Typography>{!assignedToMe && <Alert severity="info" sx={{ mt: 2 }}>Only the assigned officer can update this case.</Alert>}{assignedToMe && <Stack spacing={2} sx={{ mt: 2 }}>{(item.status === 'Assigned' || item.status === 'Reopened') && <Button variant="contained" disabled={busy} onClick={() => status('InProgress')}>Start work</Button>}{item.status === 'InProgress' && <><Button variant="outlined" disabled={busy} onClick={() => status('WaitingForResident')}>Request information</Button><TextField multiline minRows={3} label="Resolution summary (at least 10 characters)" value={resolutionSummary} onChange={e => setResolutionSummary(e.target.value)} /><Button color="success" variant="contained" disabled={busy || resolutionSummary.trim().length < 10} onClick={() => status('Resolved', resolutionSummary)}>Resolve</Button></>}{item.status === 'WaitingForResident' && <Button variant="contained" disabled={busy} onClick={() => status('InProgress')}>Resume</Button>}{!['Assigned', 'Reopened', 'InProgress', 'WaitingForResident'].includes(item.status) && <Typography color="text.secondary">No officer action is available for the current status.</Typography>}</Stack>}</Paper>}
      {resident && item.status === 'Resolved' && <Button variant="outlined" color="warning" disabled={busy} onClick={() => setConfirmReopen(true)}>Reopen request</Button>}</Stack></Grid></Grid>
    <ConfirmActionDialog open={confirmReopen} title="Reopen this request?" description="The original service target and history will be retained. Tell the service team why further work is needed." confirmLabel="Confirm reopen" busy={busy} confirmDisabled={reopenReason.trim().length < 10} onCancel={() => setConfirmReopen(false)} onConfirm={() => { void status('Reopened', reopenReason).then(ok => { if (ok) setConfirmReopen(false) }) }}><TextField autoFocus fullWidth multiline minRows={3} label="Reason (at least 10 characters)" value={reopenReason} onChange={e => setReopenReason(e.target.value)} /></ConfirmActionDialog>
    <Snackbar open={Boolean(notice)} autoHideDuration={3500} onClose={() => setNotice('')} message={notice} />
  </Stack>
}

function Feed({ title, items }: { title: string; items: Activity[] }) {
  return <Paper sx={{ p: 3 }}><Typography variant="h6" sx={{ fontWeight: 800 }}>{title}</Typography><Stack spacing={2} sx={{ mt: 2 }}>{items.map(a => <Box key={a.id} sx={{ pl: 2, borderLeft: '3px solid', borderColor: a.isPublic ? 'primary.main' : 'warning.main' }}><Typography sx={{ fontWeight: 700 }}>{a.label}</Typography><Typography sx={{ whiteSpace: 'pre-wrap' }}>{a.message}</Typography><Typography variant="caption" color="text.secondary">{new Date(a.createdAtUtc).toLocaleString()} · {a.actorName}</Typography></Box>)}{items.length === 0 && <Typography color="text.secondary">No entries yet.</Typography>}</Stack></Paper>
}
function SlaTarget({ label, due, completed, state }: { label: string; due?: string; completed?: string; state: string }) {
  return <Stack spacing={0.5}><Stack direction="row" sx={{ justifyContent: 'space-between', alignItems: 'center' }}><Typography sx={{ fontWeight: 800 }}>{label}</Typography><SlaStatus state={state} /></Stack><Typography variant="body2" color="text.secondary">Due {due ? new Date(due).toLocaleString() : 'not set'}</Typography>{completed && <Typography variant="body2" color="text.secondary">Completed {new Date(completed).toLocaleString()}</Typography>}{!completed && state !== 'Complete' && <Typography variant="body2">{slaRemaining(due)}</Typography>}</Stack>
}
const format = (value: string) => ({ WaitingForResident: 'Waiting for resident', InProgress: 'In progress', OnTrack: 'On track', AtRisk: 'At risk' }[value] ?? value)
const toLocal = (value?: string) => value ? new Date(new Date(value).getTime() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16) : ''
function slaRemaining(value?: string) { if (!value) return 'SLA not set'; const hours = Math.round((new Date(value).getTime() - Date.now()) / 3600000); return hours < 0 ? `${Math.abs(hours)}h overdue` : `${hours}h remaining` }
const residentProgress = (status: string) => ({ Submitted: 'Your request has been received.', Triaged: 'The service team has reviewed your request.', Assigned: 'Your request is ready for service work.', InProgress: 'Work is in progress.', WaitingForResident: 'The service team is waiting for your reply.', Resolved: 'The service team has resolved this request.', Closed: 'This request is closed.', Reopened: 'Your request has been reopened for further work.', Rejected: 'This request is not proceeding.' }[status] ?? 'Your request is being reviewed.')
