import { useEffect, useState } from 'react'
import { Alert, Button, Chip, Grid, LinearProgress, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material'
import DownloadRoundedIcon from '@mui/icons-material/DownloadRounded'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { api, apiDownload, type Category, type ChartRow, type DashboardData, type Officer } from '../api/client'
import { useAuth } from '../auth/AuthContext'

const priorities = ['Low', 'Medium', 'High', 'Critical']; const statuses = ['Submitted', 'Triaged', 'Assigned', 'InProgress', 'WaitingForResident', 'Resolved', 'Closed', 'Reopened', 'Rejected']

export function DashboardPage() {
  const { user } = useAuth(); const canAssign = user?.roles.some(x => x === 'TeamManager' || x === 'SystemAdministrator') ?? false
  const navigate = useNavigate()
  const [params, setParams] = useSearchParams(); const query = params.toString()
  const [data, setData] = useState<DashboardData | null>(null); const [categories, setCategories] = useState<Category[]>([]); const [officers, setOfficers] = useState<Officer[]>([]); const [error, setError] = useState('')
  useEffect(() => { api<Category[]>('/categories?includeInactive=true').then(setCategories) }, [])
  useEffect(() => { if (canAssign) api<Officer[]>('/officers').then(setOfficers) }, [canAssign])
  useEffect(() => { api<DashboardData>(`/dashboard${query ? `?${query}` : ''}`).then(setData).catch(e => setError(e instanceof Error ? e.message : 'Unable to load dashboard')) }, [query])
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); setParams(next) }
  const queueLink = (extra: Record<string, string>) => { const next = new URLSearchParams(params); Object.entries(extra).forEach(([key, value]) => { if (value) next.set(key, value); else next.delete(key) }); return `/cases?${next}` }
  const exportCsv = () => apiDownload(`/reports/cases.csv${query ? `?${query}` : ''}`, 'civicflow-cases.csv').catch(e => setError(e instanceof Error ? e.message : 'Export failed'))
  if (error) return <Alert severity="error">{error}</Alert>
  return <Stack spacing={4}><Stack direction={{ xs: 'column', md: 'row' }} sx={{ justifyContent: 'space-between', gap: 2 }}><div><Typography variant="h3">Operations dashboard</Typography><Typography color="text.secondary">Interactive workload, SLA and service-performance view.</Typography></div>{canAssign && <Button startIcon={<DownloadRoundedIcon />} variant="outlined" onClick={exportCsv}>Export filtered CSV</Button>}</Stack>
    <Paper sx={{ p: 2 }}><Stack direction={{ xs: 'column', md: 'row' }} spacing={2} useFlexGap sx={{ flexWrap: 'wrap' }}><TextField size="small" type="date" label="Submitted from" value={params.get('submittedFrom')?.slice(0, 10) ?? ''} onChange={e => update('submittedFrom', e.target.value)} slotProps={{ inputLabel: { shrink: true } }} /><TextField size="small" type="date" label="Submitted to" value={params.get('submittedTo')?.slice(0, 10) ?? ''} onChange={e => update('submittedTo', e.target.value)} slotProps={{ inputLabel: { shrink: true } }} /><Filter label="Category" value={params.get('categoryId') ?? ''} onChange={v => update('categoryId', v)} options={categories.map(x => [x.id, x.name])} /><Filter label="Priority" value={params.get('priority') ?? ''} onChange={v => update('priority', v)} options={priorities.map(x => [x, x])} /><Filter label="Status" value={params.get('status') ?? ''} onChange={v => update('status', v)} options={statuses.map(x => [x, format(x)])} />{canAssign && <Filter label="Officer" value={params.get('officerId') ?? ''} onChange={v => update('officerId', v)} options={officers.map(x => [x.id, `${x.firstName} ${x.lastName}`])} />}<Button onClick={() => setParams(new URLSearchParams())}>Clear</Button></Stack></Paper>
    {!data ? <LinearProgress /> : <><Grid container spacing={2}>{[
      ['Open', data.open, { quickView: 'open' }], ['Unassigned', data.unassigned, { unassigned: 'true', quickView: 'open' }], ['At risk', data.atRisk, { slaState: 'AtRisk' }], ['Overdue', data.overdue, { slaState: 'Overdue' }], ['Waiting for resident', data.waitingForResident, { status: 'WaitingForResident' }], ['Resolved', data.resolved, { status: 'Resolved' }]
    ].map(([label, value, filter]) => <Grid size={{ xs: 6, md: 2 }} key={label as string}><Paper component={Link} to={queueLink(filter as Record<string, string>)} sx={{ p: 2.5, display: 'block', color: 'inherit', textDecoration: 'none', '&:hover': { borderColor: 'primary.main' } }}><Typography color="text.secondary">{label as string}</Typography><Typography variant="h3" sx={{ fontWeight: 850 }}>{value as number}</Typography></Paper></Grid>)}</Grid>
      <Grid container spacing={3}><Chart title="Cases by status" rows={data.byStatus} /><Chart title="Cases by priority" rows={data.byPriority} /><Chart title="Cases by category" rows={data.byCategory} /><Chart title="Active officer workload" rows={data.officerWorkload} /></Grid>
      <Paper sx={{ overflowX: 'auto' }}><Stack sx={{ p: 3 }}><Typography variant="h5" sx={{ fontWeight: 800 }}>SLA at-risk and overdue cases</Typography><Typography color="text.secondary">The next ten cases requiring attention.</Typography></Stack><Table><TableHead><TableRow><TableCell>Reference</TableCell><TableCell>Title</TableCell><TableCell>Category</TableCell><TableCell>Priority</TableCell><TableCell>Status</TableCell><TableCell>SLA due</TableCell><TableCell>State</TableCell></TableRow></TableHead><TableBody>{data.slaCases.map(item => <TableRow hover key={item.id} onClick={() => navigate(`/cases/${item.id}`)} sx={{ cursor: 'pointer' }}><TableCell><strong>{item.referenceNumber}</strong></TableCell><TableCell>{item.title}</TableCell><TableCell>{item.categoryName}</TableCell><TableCell>{item.priority}</TableCell><TableCell>{format(item.status)}</TableCell><TableCell>{item.resolutionDueAtUtc ? new Date(item.resolutionDueAtUtc).toLocaleString() : '—'}</TableCell><TableCell><Chip size="small" color={item.slaState === 'Overdue' ? 'error' : 'warning'} label={format(item.slaState)} /></TableCell></TableRow>)}{data.slaCases.length === 0 && <TableRow><TableCell colSpan={7}>No at-risk or overdue cases in this view.</TableCell></TableRow>}</TableBody></Table></Paper>
    </>}
  </Stack>
}

function Filter({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <TextField select size="small" label={label} value={value} onChange={e => onChange(e.target.value)} sx={{ minWidth: 150 }}><MenuItem value="">All</MenuItem>{options.map(([id, name]) => <MenuItem key={id} value={id}>{name}</MenuItem>)}</TextField> }
function Chart({ title, rows }: { title: string; rows: ChartRow[] }) { const max = Math.max(...rows.map(x => x.count), 1); return <Grid size={{ xs: 12, md: 6 }}><Paper sx={{ p: 3, height: '100%' }}><Typography variant="h5" sx={{ mb: 3, fontWeight: 800 }}>{title}</Typography><Stack spacing={2}>{rows.map(row => <div key={row.label}><Stack direction="row" sx={{ justifyContent: 'space-between' }}><Typography>{format(row.label)}</Typography><Typography sx={{ fontWeight: 700 }}>{row.count}</Typography></Stack><LinearProgress variant="determinate" value={row.count / max * 100} sx={{ mt: 1, height: 8, borderRadius: 4 }} /></div>)}{rows.length === 0 && <Typography color="text.secondary">No data for the current filters.</Typography>}</Stack></Paper></Grid> }
const format = (value: string) => ({ WaitingForResident: 'Waiting for resident', InProgress: 'In progress', OnTrack: 'On track', AtRisk: 'At risk', NoSla: 'No SLA' }[value] ?? value)
