import { useCallback, useEffect, useState } from 'react'
import { Button, Grid, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material'
import DownloadRoundedIcon from '@mui/icons-material/DownloadRounded'
import { Link, useSearchParams } from 'react-router-dom'
import { api, apiDownload, type Category, type DashboardData, type Officer } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import { EmptyState, ErrorState, PageHeader, PriorityChip, SlaStatus, StatusChip, TableSkeleton } from '../components/ui'
import { ActiveFilterSummary, ResponsiveDataView } from '../components/resident'
import { CompactChart, DashboardKpiCard, SlaWorkItemCard } from '../components/staff'
import { formatDateTime, formatStatus } from '../components/formatting'

const priorities = ['Low', 'Medium', 'High', 'Critical']; const statuses = ['Submitted', 'Triaged', 'Assigned', 'InProgress', 'WaitingForResident', 'Resolved', 'Closed', 'Reopened', 'Rejected']

export function DashboardPage() {
  const { user } = useAuth(); const canAssign = user?.roles.some(role => role === 'TeamManager' || role === 'SystemAdministrator') ?? false
  const [params, setParams] = useSearchParams(); const query = params.toString(); const [data, setData] = useState<DashboardData | null>(null); const [categories, setCategories] = useState<Category[]>([]); const [officers, setOfficers] = useState<Officer[]>([]); const [error, setError] = useState('')
  useEffect(() => { void api<Category[]>('/categories?includeInactive=true').then(setCategories) }, []); useEffect(() => { if (canAssign) void api<Officer[]>('/officers').then(setOfficers) }, [canAssign])
  const load = useCallback(() => api<DashboardData>(`/dashboard${query ? `?${query}` : ''}`).then(setData).catch(reason => setError(reason instanceof Error ? reason.message : 'Unable to load dashboard')), [query])
  useEffect(() => { void load() }, [load])
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); setParams(next) }
  const clear = () => setParams(new URLSearchParams()); const queueLink = (extra: Record<string, string>) => { const next = new URLSearchParams(params); Object.entries(extra).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); return `/cases?${next}` }
  const exportCsv = () => apiDownload(`/reports/cases.csv${query ? `?${query}` : ''}`, 'civicflow-cases.csv').catch(reason => setError(reason instanceof Error ? reason.message : 'Export failed'))
  return <Stack spacing={4} aria-busy={!data && !error}><PageHeader title="Operations dashboard" description="Team workload, service targets and cases needing attention." actions={canAssign && <Button startIcon={<DownloadRoundedIcon />} variant="outlined" onClick={exportCsv}>Export filtered CSV</Button>} />
    <Paper sx={{ p: 3 }}><Stack direction={{ xs: 'column', md: 'row' }} spacing={2} useFlexGap sx={{ flexWrap: 'wrap' }}><TextField size="small" type="date" label="Submitted from" value={params.get('submittedFrom')?.slice(0, 10) ?? ''} onChange={event => update('submittedFrom', event.target.value)} slotProps={{ inputLabel: { shrink: true } }} /><TextField size="small" type="date" label="Submitted to" value={params.get('submittedTo')?.slice(0, 10) ?? ''} onChange={event => update('submittedTo', event.target.value)} slotProps={{ inputLabel: { shrink: true } }} /><Filter label="Category" value={params.get('categoryId') ?? ''} onChange={value => update('categoryId', value)} options={categories.map(item => [item.id, item.name])} /><Filter label="Priority" value={params.get('priority') ?? ''} onChange={value => update('priority', value)} options={priorities.map(item => [item, item])} /><Filter label="Status" value={params.get('status') ?? ''} onChange={value => update('status', value)} options={statuses.map(item => [item, formatStatus(item)])} />{canAssign && <Filter label="Officer" value={params.get('officerId') ?? ''} onChange={value => update('officerId', value)} options={officers.map(item => [item.id, `${item.firstName} ${item.lastName}`])} />}{query && <Button onClick={clear}>Clear filters</Button>}</Stack></Paper>
    {query && <ActiveFilterSummary search={params.get('categoryId') ? 'Filtered dashboard' : undefined} status={params.get('status') ?? params.get('priority') ?? undefined} onClear={clear} />}
    {error && <ErrorState title="Unable to load dashboard" message={error} retry={() => { setError(''); setData(null); void load() }} />}
    {!data && !error && <Paper><TableSkeleton rows={6} columns={4} label="Loading dashboard" /></Paper>}
    {data && <><Grid container spacing={2}>{[
      ['Open', data.open, 'Cases still requiring service work', { quickView: 'open' }], ['Unassigned', data.unassigned, 'Open cases awaiting assignment', { unassigned: 'true', quickView: 'open' }], ['At risk', data.atRisk, 'Cases approaching a service target', { slaState: 'AtRisk' }], ['Overdue', data.overdue, 'Cases with an overdue target', { slaState: 'Overdue' }], ['Waiting for resident', data.waitingForResident, 'Cases awaiting resident information', { status: 'WaitingForResident' }], ['Resolved', data.resolved, 'Cases resolved in this view', { status: 'Resolved' }]
    ].map(([label, value, description, filter]) => <Grid size={{ xs: 12, sm: 6, lg: 2 }} key={label as string}><DashboardKpiCard label={label as string} value={value as number} description={description as string} to={queueLink(filter as Record<string, string>)} /></Grid>)}</Grid>
      <Grid container spacing={3}><Grid size={{ xs: 12, md: 6 }}><CompactChart title="Cases by status" description="Current case distribution by workflow state." rows={data.byStatus.map(row => ({ ...row, label: formatStatus(row.label) }))} /></Grid><Grid size={{ xs: 12, md: 6 }}><CompactChart title="Cases by priority" description="Current workload by operational priority." rows={data.byPriority} /></Grid><Grid size={{ xs: 12, md: 6 }}><CompactChart title="Cases by category" description="Case volume across service categories." rows={data.byCategory} /></Grid><Grid size={{ xs: 12, md: 6 }}><CompactChart title="Active officer workload" description="Non-terminal cases currently assigned to each officer." rows={data.officerWorkload} /></Grid></Grid>
      <ResponsiveDataView desktop={<Paper sx={{ overflowX: 'auto' }}><Stack sx={{ p: 3 }}><Typography variant="h5">SLA at-risk and overdue cases</Typography><Typography color="text.secondary">The next ten cases requiring attention, using the earliest incomplete target.</Typography></Stack><Table><TableHead><TableRow><TableCell>Reference</TableCell><TableCell>Title</TableCell><TableCell>Priority</TableCell><TableCell>Status</TableCell><TableCell>Officer</TableCell><TableCell>Due</TableCell><TableCell>State</TableCell></TableRow></TableHead><TableBody>{data.slaCases.map(item => <TableRow key={item.id}><TableCell><Button component={Link} to={`/cases/${item.id}`} sx={{ minHeight: 44 }}>{item.referenceNumber}</Button></TableCell><TableCell>{item.title}</TableCell><TableCell><PriorityChip priority={item.priority} /></TableCell><TableCell><StatusChip status={item.status} /></TableCell><TableCell>{item.assignedOfficerName ?? 'Not assigned'}</TableCell><TableCell>{item.nextSlaDueAtUtc ? formatDateTime(item.nextSlaDueAtUtc) : 'Not set'}</TableCell><TableCell><SlaStatus state={item.slaState} /></TableCell></TableRow>)}{!data.slaCases.length && <TableRow><TableCell colSpan={7}><EmptyState title="No urgent SLA cases" description="No at-risk or overdue cases match the current filters." /></TableCell></TableRow>}</TableBody></Table></Paper>} mobile={<Stack spacing={3}>{data.slaCases.map(item => <SlaWorkItemCard key={item.id} item={item} />)}{!data.slaCases.length && <Paper><EmptyState title="No urgent SLA cases" description="No at-risk or overdue cases match the current filters." /></Paper>}</Stack>} />
    </>}
  </Stack>
}

function Filter({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <TextField select size="small" label={label} value={value} onChange={event => onChange(event.target.value)} sx={{ minWidth: 150 }}><MenuItem value="">All</MenuItem>{options.map(([id, name]) => <MenuItem key={id} value={id}>{name}</MenuItem>)}</TextField> }
