import { render, screen } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { ThemeProvider } from '@mui/material'
import axe from 'axe-core'
import { describe, expect, it } from 'vitest'
import { civicTheme } from '../theme'
import { AdminUserCard, AuditEventCard, CategorySlaCard, RoleLabel, duration, hasAuditFilters, resolveAdminSection, roleLabel, updateAdminQuery } from './admin'
const wrap = (node: React.ReactNode) => <ThemeProvider theme={civicTheme}><MemoryRouter>{node}</MemoryRouter></ThemeProvider>
describe('admin and audit components', () => {
  it('maps internal role values to friendly labels', () => { expect(roleLabel('CaseOfficer')).toBe('Service officer'); expect(roleLabel('TeamManager')).toBe('Team manager'); render(wrap(<RoleLabel role="SystemAdministrator" />)); expect(screen.getByText('System administrator')).toBeVisible() })
  it('separates user status from supplied actions', () => { render(wrap(<AdminUserCard user={{ firstName: 'Alex', lastName: 'Admin', email: 'admin@example.com', roles: ['SystemAdministrator'], isActive: true, createdAtUtc: '2026-09-02T00:00:00Z' }} self actions={<button disabled>Disable account</button>} />)); expect(screen.getByText('Active')).toBeVisible(); expect(screen.getByRole('button', { name: 'Disable account' })).toBeDisabled(); expect(screen.getByText(/cannot disable your own account/i)).toBeVisible() })
  it('expresses category targets in hours and days', () => { render(wrap(<CategorySlaCard category={{ name: 'Roads', description: 'Road requests', firstResponseHours: 8, resolutionHours: 72, isActive: true }} actions={<button>Edit</button>} />)); expect(screen.getByText('3 days (72 hours)')).toBeVisible(); expect(duration(1)).toBe('1 hour') })
  it('renders audit events as read-only cards with a case link and wrapping-safe actor identity', () => { render(wrap(<AuditEventCard row={{ action: 'PriorityChanged', message: 'Priority changed.', createdAtUtc: '2026-09-02T00:00:00Z', serviceRequestId: 'case-1', userName: 'Morgan Manager', userEmail: 'manager@example.com', referenceNumber: 'CF-1' }} />)); expect(screen.getByText('Priority Changed')).toBeVisible(); expect(screen.getByText('manager@example.com')).toBeVisible(); expect(screen.getByRole('link', { name: 'CF-1' })).toHaveAttribute('href', '/cases/case-1') })
  it('maps administration sections and audit filters to URL state', () => { expect(resolveAdminSection(new URLSearchParams('section=categories'))).toBe('categories'); expect(resolveAdminSection(new URLSearchParams('section=unknown'))).toBe('users'); const next = updateAdminQuery(new URLSearchParams('page=3&pageSize=50'), 'action', 'Assigned'); expect(next.toString()).toContain('action=Assigned'); expect(next.get('page')).toBe('1'); expect(hasAuditFilters(next)).toBe(true); expect(hasAuditFilters(new URLSearchParams('page=2&pageSize=25'))).toBe(false) })
  it('has no serious or critical axe violations', async () => { const { container } = render(wrap(<AuditEventCard row={{ action: 'Assigned', message: 'Assigned.', createdAtUtc: '2026-09-02T00:00:00Z', serviceRequestId: 'case-1' }} />)); const results = await axe.run(container); expect(results.violations.filter(result => ['serious', 'critical'].includes(result.impact ?? ''))).toEqual([]) })
})
